# Neural Networks

In [11]:
%load_ext autoreload
%autoreload 2
# Autoreload is a Jupyter extension that allows you to automatically reload modules when they are changed.

import h5py
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import torch
from torch import nn
import os

import utils # This is some scripts that will help us with the project. You can find them in the /utils folder.

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
device

device(type='cuda')

In [2]:
tensor_size = 10000
random_tensor = torch.randn(tensor_size, tensor_size)


In [3]:
# time this!
import time
start_time = time.time()
random_tensor2 = torch.pow(random_tensor, 2)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")


Time taken: 0.06964421272277832 seconds


In [7]:
random_tensor = random_tensor.to(device)

In [8]:
random_tensor

tensor([[ 0.4462,  1.1213, -0.7229,  ...,  0.2573, -0.2233,  0.1506],
        [ 0.9413,  0.1020, -0.8540,  ...,  0.1761, -1.8104, -0.3978],
        [ 1.5248, -0.0449,  0.3565,  ...,  0.2384,  0.5859,  0.2412],
        ...,
        [-1.1399,  1.8997, -0.3371,  ...,  0.3072, -0.1097,  1.2630],
        [-0.6871,  1.3231,  0.7395,  ..., -0.1223, -1.5868, -0.5016],
        [ 0.2588,  0.8003, -1.2684,  ..., -0.1406,  0.6304,  0.0358]],
       device='cuda:0')

In [9]:
# time this!
import time
start_time = time.time()
random_tensor2 = torch.pow(random_tensor, 2)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")


Time taken: 0.19625186920166016 seconds


In [10]:
# time this!
import time
start_time = time.time()
random_tensor2 = torch.pow(random_tensor, 2)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")


Time taken: 0.00044536590576171875 seconds


# Write a neural network!

In [14]:
def square_this(x):
    return x**2

square_this(5)

25

In [23]:
class apple:
    def __init__(self, color, size):
        self.color = color
        self.size = size
        
    def __str__(self):
        return f"apple"

    def eat(self):
        print("eating apple")
        self.size = "eaten"
    

In [ ]:
my_favorite_apple = apple("red", "small")
print(my_favorite_apple)

apple


In [27]:
my_favorite_apple.size

'small'

In [28]:
my_favorite_apple.eat()

eating apple


In [29]:
my_favorite_apple.size

'eaten'

In [18]:
my_favorite_apple.color

'red'

In [19]:
my_favorite_apple.size

'small'

In [12]:
class my_cool_class():
    def __init__(self):
        self.name = "my_cool_class"
        
    def __str__(self):
        return f"my_cool_class"
    
    

In [13]:
example_of_my_cool_class = my_cool_class()
print(example_of_my_cool_class)






my_cool_class


In [75]:
class cool_neural_network(nn.Module):
    def __init__(self):
        super(cool_neural_network, self).__init__()
        self.name = "cool_neural_network"

        self.layer1 = nn.Linear(10, 10)
        self.layer2 = nn.Linear(10, 10)
        self.layer3 = nn.Linear(10, 1)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.activation(self.layer1(x))
        x = self.activation(self.layer2(x))
        x = self.layer3(x)
        return x




In [84]:
my_cool_neural_network = cool_neural_network()
print(my_cool_neural_network)

cool_neural_network(
  (layer1): Linear(in_features=10, out_features=10, bias=True)
  (layer2): Linear(in_features=10, out_features=10, bias=True)
  (layer3): Linear(in_features=10, out_features=1, bias=True)
  (activation): ReLU()
)


In [85]:
dataset = torch.randn(100, 10)
dataset
# outputs = my_cool_neural_network(dataset)

tensor([[-1.9847e+00,  4.6584e-01, -9.3128e-01,  6.3345e-01,  3.8172e-01,
          1.4479e+00, -1.1587e-01, -1.3192e+00, -5.9024e-01, -1.4643e-01],
        [ 4.2310e-01, -3.8643e-01,  1.2951e-01, -1.3118e+00,  1.6393e+00,
          5.5344e-01,  9.0246e-01, -4.3306e-01, -1.6332e+00,  5.8033e-01],
        [ 1.6453e-01, -1.3133e-01,  1.9453e+00,  1.0523e+00,  1.1570e-01,
         -3.4954e-01,  2.1532e+00,  3.4796e-01, -3.5155e-02,  3.7994e-01],
        [ 2.8388e-01,  7.3816e-01,  1.1549e+00,  1.7954e+00, -8.3214e-01,
         -8.3960e-01,  1.1054e+00, -1.1628e+00,  5.5197e-01,  1.1237e+00],
        [-6.5462e-01,  1.3033e+00,  6.2748e-02, -1.1578e+00, -5.9968e-01,
          4.3977e-02, -1.1435e+00,  1.2041e+00,  1.5217e+00, -1.0967e+00],
        [-1.1705e+00, -3.5335e-01, -9.9875e-01,  3.6669e-01,  2.4510e-01,
         -7.9736e-02,  1.3122e+00, -7.8071e-01,  2.9610e-01,  8.3121e-01],
        [-2.6814e+00, -1.0131e-01,  1.1240e+00,  9.9500e-01, -1.2785e+00,
          7.9797e-02, -6.9978e-0

In [86]:
truth = torch.zeros(100, 1)

In [89]:
loss_function = nn.MSELoss()
optimizer = torch.optim.AdamW(my_cool_neural_network.parameters(), lr=0.0001)

In [90]:
num_epochs = 100

for epoch in range(num_epochs):
    optimizer.zero_grad()
    outputs = my_cool_neural_network(dataset)
    loss = (outputs - truth)**2
    loss = loss.sum()
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch} loss: {loss.item()}")
    print("average output: ", outputs.mean())

Epoch 0 loss: 0.6087172627449036
average output:  tensor(-0.0277, grad_fn=<MeanBackward0>)
Epoch 1 loss: 0.6053330302238464
average output:  tensor(-0.0275, grad_fn=<MeanBackward0>)
Epoch 2 loss: 0.6019687652587891
average output:  tensor(-0.0273, grad_fn=<MeanBackward0>)
Epoch 3 loss: 0.5986266732215881
average output:  tensor(-0.0271, grad_fn=<MeanBackward0>)
Epoch 4 loss: 0.5953052043914795
average output:  tensor(-0.0268, grad_fn=<MeanBackward0>)
Epoch 5 loss: 0.5920047760009766
average output:  tensor(-0.0266, grad_fn=<MeanBackward0>)
Epoch 6 loss: 0.5887268781661987
average output:  tensor(-0.0264, grad_fn=<MeanBackward0>)
Epoch 7 loss: 0.5854699015617371
average output:  tensor(-0.0262, grad_fn=<MeanBackward0>)
Epoch 8 loss: 0.5822345018386841
average output:  tensor(-0.0260, grad_fn=<MeanBackward0>)
Epoch 9 loss: 0.5790184736251831
average output:  tensor(-0.0258, grad_fn=<MeanBackward0>)
Epoch 10 loss: 0.5758236050605774
average output:  tensor(-0.0256, grad_fn=<MeanBackward0>

In [67]:
outputs

tensor([[-0.1175],
        [-0.0940],
        [-0.1507],
        [-0.0316],
        [ 0.1226],
        [-0.1018],
        [-0.1683],
        [-0.1345],
        [-0.1438],
        [-0.1045],
        [-0.1621],
        [-0.1479],
        [-0.1612],
        [-0.2049],
        [-0.0346],
        [-0.1986],
        [-0.1094],
        [-0.0521],
        [-0.1374],
        [-0.1729],
        [-0.0928],
        [-0.1338],
        [-0.0319],
        [-0.2052],
        [-0.1326],
        [-0.1887],
        [-0.0627],
        [-0.1278],
        [-0.2132],
        [-0.1985],
        [-0.1097],
        [-0.1793],
        [-0.1842],
        [-0.0972],
        [-0.1125],
        [-0.0973],
        [-0.0562],
        [-0.1414],
        [-0.1663],
        [-0.1775],
        [-0.1550],
        [-0.0660],
        [-0.1185],
        [-0.1088],
        [-0.0685],
        [-0.1836],
        [-0.0170],
        [-0.1520],
        [-0.0344],
        [-0.1127],
        [-0.1561],
        [-0.1167],
        [-0.

In [65]:
loss

tensor(0.0174, grad_fn=<MseLossBackward0>)

In [ ]:
import pytorch_lightning as pl
from torch.utils.data import TensorDataset, DataLoader

class LightningNeuralNetwork(pl.LightningModule):
    def __init__(self, input_size=10, hidden_size=20, output_size=1, learning_rate=0.0001):
        super().__init__()
        self.model = cool_neural_network()
        self.learning_rate = learning_rate
        self.loss_function = nn.MSELoss()
        
    def forward(self, x):
        return self.model(x)
    
    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = self.loss_function(y_hat, y)
        self.log('train_loss', loss)
        return loss
    
    def configure_optimizers(self):
        return torch.optim.AdamW(self.parameters(), lr=self.learning_rate)

# Create a PyTorch Lightning model
lightning_model = LightningNeuralNetwork(learning_rate=0.0001)

# Create a dataset and dataloader
tensor_dataset = TensorDataset(dataset, truth)
train_loader = DataLoader(tensor_dataset, batch_size=32)

# Create a trainer
trainer = pl.Trainer(max_epochs=100)

# Train the model
trainer.fit(lightning_model, train_loader)

# Get predictions after training
with torch.no_grad():
    lightning_outputs = lightning_model(dataset)
    lightning_loss = loss_function(lightning_outputs, truth)

print(f"Final loss: {lightning_loss.item()}")
print(f"Average output: {lightning_outputs.mean().item()}")


In [101]:
ttbar_base_dir = "/global/cfs/cdirs/m4958/data/ColliderML/staging/pileup-10/ttbar/v1/reco/tracks"
ttbar_dataset_name = "pileup-10.ttbar.v1.reco"

ttbar_all_tracks_df = utils.read_events_tracks(ttbar_base_dir, range(1000), ttbar_dataset_name)

susy_base_dir = "/global/cfs/cdirs/m4958/data/ColliderML/staging/pileup-10/susy/v1/reco/tracks"
susy_dataset_name = "pileup-10.susy.v1.reco"

susy_all_tracks_df = utils.read_events_tracks(susy_base_dir, range(1000), susy_dataset_name)

In [102]:
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from torch.utils.data import TensorDataset, DataLoader

def prepare_event_features(df_group, n_tracks=10, features=['d0_truth', 'z0_truth', 'phi_truth', 
                                                          'theta_truth', 'charge_truth', 'p_truth', 'pT_truth']):
    """
    Prepare fixed-length feature vector for an event by taking top N tracks sorted by pT
    
    Args:
        df_group: DataFrame group containing all tracks for one event
        n_tracks: Number of top tracks to keep
        features: List of track features to use
    
    Returns:
        Numpy array of concatenated features with shape (n_tracks * len(features),)
    """
    # Sort tracks by pT
    sorted_tracks = df_group.sort_values('pT_truth', ascending=False)
    
    # Initialize array for fixed number of tracks
    track_features = np.zeros((n_tracks, len(features)))
    
    # Fill available tracks
    n_available = min(len(sorted_tracks), n_tracks)
    track_features[:n_available] = sorted_tracks[features].iloc[:n_available].values
    
    # Flatten array to 1D
    return track_features.flatten()

def prepare_dataset(df, n_tracks=10):
    """
    Prepare features for all events in the dataset
    
    Args:
        df: DataFrame containing all tracks from all events
        n_tracks: Number of top tracks to keep per event
    
    Returns:
        X: Array of shape (n_events, n_tracks * n_features)
    """
    features = ['d0_truth', 'z0_truth', 'phi_truth', 'theta_truth',
               'charge_truth', 'p_truth', 'pT_truth']
    
    # Group by event_id and prepare features for each event
    X = np.array([
        prepare_event_features(group, n_tracks, features) 
        for _, group in df.groupby('event_id')
    ])
    
    return X

# Example of how to use these functions with your data:
number_of_tracks = 10
X_ttbar = prepare_dataset(ttbar_all_tracks_df, n_tracks=number_of_tracks)
X_susy = prepare_dataset(susy_all_tracks_df, n_tracks=number_of_tracks)

# Create labels (0 for ttbar, 1 for susy)
y_ttbar = np.zeros(len(X_ttbar))
y_susy = np.ones(len(X_susy))

# Combine datasets
X = np.vstack([X_ttbar, X_susy])
y = np.concatenate([y_ttbar, y_susy])

# Convert to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32).to(device)
y_tensor = torch.tensor(y, dtype=torch.float32).view(-1, 1).to(device)

# Create dataset and dataloader
tensor_dataset = TensorDataset(X_tensor, y_tensor)
train_loader = DataLoader(tensor_dataset, batch_size=32, shuffle=True)


In [96]:
tensor_dataset[0]

(tensor([-5.7436e-03, -1.0537e+02,  1.1139e+00,  2.0434e+00, -1.0000e+00,
          3.1966e+01,  2.8462e+01, -2.5322e-03, -1.0536e+02,  1.7370e+00,
          4.2169e-01,  1.0000e+00,  6.6719e+01,  2.7309e+01, -3.2243e-04,
         -1.0537e+02,  2.0708e+00,  1.0312e+00, -1.0000e+00,  2.5829e+01,
          2.2159e+01, -3.4987e-04, -1.0537e+02,  2.0667e+00,  1.0049e+00,
          1.0000e+00,  1.5484e+01,  1.3070e+01, -8.4947e-04, -1.0537e+02,
          1.9930e+00,  1.0846e+00,  1.0000e+00,  9.0140e+00,  7.9695e+00,
         -1.6596e-02, -2.4865e+00,  1.9797e+00,  1.0837e-01, -1.0000e+00,
          3.6000e+01,  3.8936e+00, -1.1101e-03, -1.0537e+02,  1.9543e+00,
          9.5791e-01, -1.0000e+00,  4.5086e+00,  3.6880e+00,  4.9950e-03,
         -1.0537e+02, -1.8473e+00,  1.2326e+00,  1.0000e+00,  3.8303e+00,
          3.6133e+00, -1.9655e-03, -1.0536e+02,  1.8252e+00,  4.2553e-01,
         -1.0000e+00,  8.3296e+00,  3.4384e+00,  1.2146e-01, -1.0503e+02,
         -2.7569e-01,  2.7024e+00, -1.

In [103]:
len(tensor_dataset)

2000

In [104]:
tensor_dataset[1500]

(tensor([-1.8132e-03,  2.0317e+01, -2.1163e+00,  2.4739e+00, -1.0000e+00,
          6.4027e+01,  3.9643e+01, -1.6053e-03,  2.0318e+01, -2.1028e+00,
          2.4687e+00, -1.0000e+00,  4.4824e+01,  2.7937e+01, -1.6583e-03,
          2.0317e+01, -2.1071e+00,  2.4767e+00,  1.0000e+00,  3.3052e+01,
          2.0393e+01, -1.6799e-03,  2.0317e+01, -2.1084e+00,  2.4778e+00,
          1.0000e+00,  3.0901e+01,  1.9038e+01,  3.1764e-04,  2.0352e+01,
         -1.9900e+00,  9.0958e-01, -1.0000e+00,  1.2822e+01,  1.0120e+01,
         -1.2821e-02,  2.0410e+01,  1.9935e+00,  2.9877e+00, -1.0000e+00,
          5.2290e+01,  8.0161e+00,  1.9092e-03,  2.0351e+01, -1.8957e+00,
          9.3777e-01,  1.0000e+00,  9.9029e+00,  7.9841e+00, -1.4175e-04,
          2.0353e+01, -2.0172e+00,  8.8240e-01, -1.0000e+00,  9.6695e+00,
          7.4674e+00, -4.3487e-03,  2.0320e+01, -2.2690e+00,  2.4140e+00,
          1.0000e+00,  1.0985e+01,  7.3057e+00, -1.3262e-02,  2.0410e+01,
          2.0345e+00,  2.9947e+00, -1.

In [ ]:
for epoch in range(100):
    for batch in train_loader:
        output = my_cool_neural_network(batch[0])
        loss = loss_function(output, batch[1])
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        print(f"Epoch {epoch} loss: {loss.item()}")
        print("average output: ", output.mean())
